# Generated by Django 5.1.15 on 2026-04-24 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('garantia_padrao_meses', models.PositiveIntegerField(default=12, help_text='Meses de garantia padrão ao cadastrar uma usina nova.')),
                ('alerta_sem_comunicacao_minutos', models.PositiveIntegerField(default=60, help_text='Quantos minutos sem comunicação antes de abrir alerta.')),
                ('parar_alerta_apos_dias', models.PositiveIntegerField(default=7, help_text='Depois de quantos dias sem comunicação parar de gerar alertas.')),
                ('subdesempenho_limite_pct', models.DecimalField(decimal_places=2, default=70, help_text='Percentual da capacidade esperada abaixo do qual alertar.', max_digits=5)),
                ('retencao_leituras_dias', models.PositiveIntegerField(default=90, help_text='Quantos dias de leituras (LeituraUsina / LeituraInversor) manter. Leituras mais antigas são apagadas por task diária. Alertas não são afetados.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracao', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Configuração da empresa',
                'verbose_name_plural': 'Configurações das empresas',
            },
        ),
    ]
