# Generated by Django 5.1.15 on 2026-04-24 22:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracaoempresa',
            name='parar_alerta_apos_dias',
        ),
        migrations.AddField(
            model_name='configuracaoempresa',
            name='alerta_dado_ausente_coletas',
            field=models.PositiveIntegerField(default=10, help_text='Número de coletas consecutivas com campo elétrico null antes de abrir alerta `dado_eletrico_ausente`.'),
        ),
        migrations.AddField(
            model_name='configuracaoempresa',
            name='garantia_aviso_dias',
            field=models.PositiveIntegerField(default=30, help_text='Dias antes do fim da garantia para abrir alerta info.'),
        ),
        migrations.AddField(
            model_name='configuracaoempresa',
            name='garantia_critico_dias',
            field=models.PositiveIntegerField(default=7, help_text='Dias antes do fim para escalar o alerta a aviso.'),
        ),
        migrations.AddField(
            model_name='configuracaoempresa',
            name='horario_solar_fim',
            field=models.TimeField(default=datetime.time(18, 0), help_text='Hora limite até a qual a usina deve estar gerando.'),
        ),
        migrations.AddField(
            model_name='configuracaoempresa',
            name='horario_solar_inicio',
            field=models.TimeField(default=datetime.time(8, 0), help_text='Hora (fuso da usina) a partir da qual a usina deve estar gerando.'),
        ),
        migrations.AddField(
            model_name='configuracaoempresa',
            name='queda_rendimento_pct',
            field=models.DecimalField(decimal_places=2, default=60, help_text='Abaixo desse % da média dos últimos 7 dias, abre queda_rendimento.', max_digits=5),
        ),
        migrations.AddField(
            model_name='configuracaoempresa',
            name='temperatura_limite_c',
            field=models.DecimalField(decimal_places=2, default=75, help_text='Limite padrão de temperatura (°C) quando o Inversor não define.', max_digits=5),
        ),
        migrations.AlterField(
            model_name='configuracaoempresa',
            name='alerta_sem_comunicacao_minutos',
            field=models.PositiveIntegerField(default=60, help_text='Minutos sem `medido_em` antes de abrir alerta.'),
        ),
        migrations.AlterField(
            model_name='configuracaoempresa',
            name='subdesempenho_limite_pct',
            field=models.DecimalField(decimal_places=2, default=30, help_text='Abaixo desse % da capacidade instalada, abre subdesempenho.', max_digits=5),
        ),
    ]
