# Generated by Django 5.1.15 on 2026-04-26 22:42

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_configuracaoempresa_parar_alerta_apos_dias_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaoempresa',
            name='inversor_offline_coletas_minimas',
            field=models.PositiveSmallIntegerField(default=3, help_text='Número de coletas consecutivas em estado=offline antes de abrir alerta inversor_offline. Evita ruído de inversores que ligam/desligam em horários levemente diferentes.'),
        ),
        migrations.AddField(
            model_name='configuracaoempresa',
            name='potencia_minima_avaliacao_kw',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.5'), help_text='Potência AC mínima (kW) para avaliar regras elétricas por inversor (frequencia_anomala, subtensao_ac). Abaixo disso o inversor está em standby/transição e leituras de tensão/frequência não são confiáveis.', max_digits=8),
        ),
        migrations.AddField(
            model_name='configuracaoempresa',
            name='sem_geracao_queda_abrupta_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('5'), help_text='% da capacidade na leitura imediatamente anterior. Se a anterior estava acima disso e agora a usina está em zero, é queda abrupta — abre sem_geracao_horario_solar. Senão (curva natural de fim de dia), não dispara.', max_digits=5),
        ),
        migrations.AlterField(
            model_name='configuracaoempresa',
            name='subdesempenho_limite_pct',
            field=models.DecimalField(decimal_places=2, default=15, help_text='Abaixo desse % da capacidade instalada, abre subdesempenho.', max_digits=5),
        ),
    ]
