# Generated by Django 5.1.15 on 2026-05-06 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alerta_sem_comunicacao_default_24h'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configuracaoempresa',
            options={'ordering': ('empresa_id',), 'verbose_name': 'Configuração da empresa', 'verbose_name_plural': 'Configurações das empresas'},
        ),
    ]
