# Generated by Django 5.1.15 on 2026-06-15 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_configuracaoempresa_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaoempresa',
            name='monitoramento_premium_aviso_dias',
            field=models.PositiveIntegerField(default=30, help_text='Dias antes do fim do contrato de monitoramento ativo (premium) para abrir alerta info.'),
        ),
        migrations.AddField(
            model_name='configuracaoempresa',
            name='monitoramento_premium_critico_dias',
            field=models.PositiveIntegerField(default=7, help_text='Dias antes do fim do contrato premium para escalar o alerta a aviso.'),
        ),
    ]
