# Generated by Django 5.1.15 on 2026-04-24 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alertas', '0001_initial'),
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EndpointWebhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('secret', models.CharField(help_text='Usado para assinar o payload.', max_length=128)),
                ('tipos_evento', models.JSONField(default=list, help_text="Ex.: ['alerta.aberto'].")),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Endpoint de webhook',
                'verbose_name_plural': 'Endpoints de webhook',
            },
        ),
        migrations.CreateModel(
            name='RegraNotificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('canal', models.CharField(choices=[('web', 'Web (in-app)'), ('email', 'E-mail'), ('webhook', 'Webhook'), ('whatsapp', 'WhatsApp')], max_length=20)),
                ('severidades', models.JSONField(default=list, help_text='Lista de severidades que disparam.')),
                ('tipos_alerta', models.JSONField(blank=True, default=list, help_text='Vazio = qualquer tipo.')),
                ('config', models.JSONField(blank=True, default=dict, help_text='Endereços, URL do webhook, etc.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Regra de notificação',
                'verbose_name_plural': 'Regras de notificação',
            },
        ),
        migrations.CreateModel(
            name='EntregaNotificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canal', models.CharField(choices=[('web', 'Web (in-app)'), ('email', 'E-mail'), ('webhook', 'Webhook'), ('whatsapp', 'WhatsApp')], max_length=20)),
                ('destino', models.CharField(max_length=500)),
                ('status', models.CharField(max_length=20)),
                ('tentativas', models.PositiveIntegerField(default=0)),
                ('ultimo_erro', models.TextField(blank=True, default='')),
                ('enviado_em', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('alerta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='alertas.alerta')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='empresas.empresa')),
                ('regra', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entregas', to='notificacoes.regranotificacao')),
            ],
            options={
                'verbose_name': 'Entrega de notificação',
                'verbose_name_plural': 'Entregas de notificação',
                'indexes': [models.Index(fields=['empresa', '-created_at', 'status'], name='notificacoe_empresa_8c41cf_idx')],
            },
        ),
    ]
