# Generated by Django 5.1.15 on 2026-04-24 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
        ('provedores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogColeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('sucesso', 'Sucesso'), ('parcial', 'Parcial'), ('erro', 'Erro'), ('auth_erro', 'Erro de autenticação')], max_length=20)),
                ('qtd_usinas', models.PositiveIntegerField(default=0)),
                ('qtd_inversores', models.PositiveIntegerField(default=0)),
                ('qtd_leituras_usina', models.PositiveIntegerField(default=0)),
                ('qtd_leituras_inversor', models.PositiveIntegerField(default=0)),
                ('qtd_alertas_abertos', models.PositiveIntegerField(default=0)),
                ('qtd_alertas_resolvidos', models.PositiveIntegerField(default=0)),
                ('detalhe_erro', models.TextField(blank=True, default='')),
                ('duracao_ms', models.PositiveIntegerField(default=0)),
                ('iniciado_em', models.DateTimeField(auto_now_add=True)),
                ('finalizado_em', models.DateTimeField(blank=True, null=True)),
                ('conta_provedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs_coleta', to='provedores.contaprovedor')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Log de coleta',
                'verbose_name_plural': 'Logs de coleta',
                'ordering': ('-iniciado_em',),
                'indexes': [models.Index(fields=['conta_provedor', '-iniciado_em'], name='coleta_logc_conta_p_5b5f79_idx'), models.Index(fields=['empresa', 'status', '-iniciado_em'], name='coleta_logc_empresa_e65874_idx')],
            },
        ),
    ]
