# Generated by Django 5.1.15 on 2026-04-24 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContaProvedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('solis', 'Solis (Ginlong)'), ('hoymiles', 'Hoymiles S-Cloud'), ('fusionsolar', 'Huawei FusionSolar'), ('solarman', 'Solarman Business'), ('auxsol', 'AuxSol Cloud'), ('foxess', 'FoxESS Cloud')], max_length=32)),
                ('rotulo', models.CharField(help_text='Nome amigável para identificar a conta.', max_length=120)),
                ('credenciais_enc', models.TextField(help_text='JSON criptografado com Fernet. Shape depende do provedor: {"api_key", "app_secret"} (Solis), {"username", "password"} (Hoymiles/FusionSolar), etc. Usar `cripto.criptografar_credenciais`.')),
                ('cache_token_enc', models.TextField(blank=True, default='', help_text='Token de sessão criptografado (Hoymiles, FusionSolar). Vazio quando o provedor é stateless (Solis HMAC-SHA1).')),
                ('cache_token_expira_em', models.DateTimeField(blank=True, null=True)),
                ('intervalo_coleta_minutos', models.PositiveIntegerField(default=30, help_text='Intervalo entre coletas em minutos. Configurável pelo usuário, mas validador rejeita valores abaixo do mínimo declarado por `CapacidadesProvedor.intervalo_minimo_minutos` no adapter.')),
                ('is_active', models.BooleanField(default=True)),
                ('precisa_atencao', models.BooleanField(default=False, help_text='Marcado quando autenticação falha — exige intervenção manual.')),
                ('ultima_sincronizacao_em', models.DateTimeField(blank=True, null=True)),
                ('ultima_sincronizacao_status', models.CharField(blank=True, choices=[('sucesso', 'Sucesso'), ('parcial', 'Parcial'), ('erro', 'Erro'), ('auth_erro', 'Erro de autenticação')], default='', max_length=20)),
                ('ultima_sincronizacao_erro', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Conta de provedor',
                'verbose_name_plural': 'Contas de provedor',
                'indexes': [models.Index(fields=['empresa', 'tipo', 'is_active'], name='provedores__empresa_f00237_idx'), models.Index(fields=['is_active', 'ultima_sincronizacao_em'], name='provedores__is_acti_5070ad_idx')],
                'constraints': [models.UniqueConstraint(fields=('empresa', 'tipo', 'rotulo'), name='conta_provedor_unica_por_empresa')],
            },
        ),
    ]
