# Generated by Django 5.1.15 on 2026-06-15 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0002_cidade_uf'),
        ('usinas', '0008_alter_usina_tensao_ac_limite_minimo_v_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoramentoAtivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio_em', models.DateField()),
                ('meses', models.PositiveIntegerField()),
                ('fim_em', models.DateField(editable=False)),
                ('valor_mensal', models.DecimalField(blank=True, decimal_places=2, help_text='Mensalidade do contrato premium (registro do contrato; opcional).', max_digits=10, null=True)),
                ('contratante', models.CharField(blank=True, default='', max_length=120)),
                ('observacoes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='empresas.empresa')),
                ('usina', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='monitoramento_ativo', to='usinas.usina')),
            ],
            options={
                'verbose_name': 'Monitoramento ativo',
                'verbose_name_plural': 'Monitoramentos ativos',
            },
        ),
    ]
