# Generated by Django 5.1.15 on 2026-06-15 21:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoramento_ativo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitoramentoativo',
            name='meses',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
