# Generated by Django 5.1.15 on 2026-04-24 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
        ('inversores', '0001_initial'),
        ('usinas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeituraInversor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coletado_em', models.DateTimeField()),
                ('medido_em', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('alerta', 'Alerta'), ('construcao', 'Em construção')], default='online', max_length=20)),
                ('pac_kw', models.DecimalField(decimal_places=3, default=0, help_text='Potência CA instantânea. 0 é válido (noite, standby).', max_digits=10)),
                ('energia_hoje_kwh', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('energia_total_kwh', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('tensao_ac_v', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('corrente_ac_a', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('frequencia_hz', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('tensao_dc_v', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('corrente_dc_a', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('temperatura_c', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('soc_bateria_pct', models.DecimalField(blank=True, decimal_places=2, help_text='% de carga da bateria; só para inversores híbridos (Solis).', max_digits=5, null=True)),
                ('strings_mppt', models.JSONField(blank=True, default=list, help_text='Lista normalizada: [{"indice": 1, "tensao_v": 39.0, "corrente_a": 6.73, "potencia_w": 262.9}, ...]. Slots zerados (Solis preenche 32 mesmo com só 2 ativos) podem ser omitidos pelo adapter para economizar espaço.')),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='empresas.empresa')),
                ('inversor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leituras', to='inversores.inversor')),
                ('usina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leituras_inversores', to='usinas.usina')),
            ],
            options={
                'verbose_name': 'Leitura de inversor',
                'verbose_name_plural': 'Leituras de inversor',
                'ordering': ('-coletado_em',),
                'indexes': [models.Index(fields=['inversor', '-coletado_em'], name='monitoramen_inverso_41ac60_idx'), models.Index(fields=['empresa', '-coletado_em'], name='monitoramen_empresa_a4bfa8_idx'), models.Index(fields=['usina', '-coletado_em'], name='monitoramen_usina_i_4a01de_idx')],
                'constraints': [models.UniqueConstraint(fields=('inversor', 'coletado_em'), name='leitura_inversor_unica_por_janela')],
            },
        ),
        migrations.CreateModel(
            name='LeituraUsina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coletado_em', models.DateTimeField(help_text='Timestamp da nossa coleta, arredondado para a janela de ingestão.')),
                ('medido_em', models.DateTimeField(blank=True, help_text='Timestamp reportado pelo provedor quando disponível. Pode ser null (FusionSolar, Foxess). Preferido para análise temporal real.', null=True)),
                ('potencia_kw', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('energia_hoje_kwh', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('energia_mes_kwh', models.DecimalField(blank=True, decimal_places=3, help_text='Foxess não expõe — fica null.', max_digits=12, null=True)),
                ('energia_total_kwh', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('alerta', 'Alerta'), ('construcao', 'Em construção')], default='online', max_length=20)),
                ('qtd_inversores_total', models.PositiveIntegerField(blank=True, null=True)),
                ('qtd_inversores_online', models.PositiveIntegerField(blank=True, null=True)),
                ('raw', models.JSONField(blank=True, default=dict, help_text='Payload bruto do provedor, preservado para auditoria e debug.')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='empresas.empresa')),
                ('usina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leituras', to='usinas.usina')),
            ],
            options={
                'verbose_name': 'Leitura de usina',
                'verbose_name_plural': 'Leituras de usina',
                'ordering': ('-coletado_em',),
                'indexes': [models.Index(fields=['usina', '-coletado_em'], name='monitoramen_usina_i_5e9722_idx'), models.Index(fields=['empresa', '-coletado_em'], name='monitoramen_empresa_09c0c9_idx')],
                'constraints': [models.UniqueConstraint(fields=('usina', 'coletado_em'), name='leitura_usina_unica_por_janela')],
            },
        ),
    ]
