# Generated by Django 5.1.15 on 2026-04-24 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
        ('usinas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inversor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_externo', models.CharField(help_text='ID do inversor no provedor (SN ou ID interno).', max_length=128)),
                ('numero_serie', models.CharField(blank=True, default='', max_length=100)),
                ('modelo', models.CharField(blank=True, default='', max_length=100)),
                ('tipo', models.CharField(choices=[('inversor', 'Inversor'), ('microinversor', 'Microinversor')], default='inversor', max_length=20)),
                ('potencia_nominal_kw', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('qtd_mppts_esperados', models.PositiveIntegerField(blank=True, help_text='Quantidade de strings/ports MPPT que este inversor tem. Usado pela regra `string_mppt_zerada` para saber quantos slots esperar em `LeituraInversor.strings_mppt`.', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('ultima_leitura_em', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='empresas.empresa')),
                ('usina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inversores', to='usinas.usina')),
            ],
            options={
                'verbose_name': 'Inversor',
                'verbose_name_plural': 'Inversores',
                'indexes': [models.Index(fields=['usina', 'is_active'], name='inversores__usina_i_610e45_idx'), models.Index(fields=['empresa', 'ultima_leitura_em'], name='inversores__empresa_902b07_idx')],
                'constraints': [models.UniqueConstraint(fields=('usina', 'id_externo'), name='inversor_unique_id_externo_por_usina')],
            },
        ),
    ]
