# Generated by Django 5.1.15 on 2026-04-24 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inversores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inversor',
            name='temperatura_limite_c',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Limite de temperatura para regra `temperatura_alta`. Null = usa default de `ConfiguracaoEmpresa.temperatura_limite_c`.', max_digits=5, null=True),
        ),
    ]
