# Generated by Django 5.1.15 on 2026-05-06 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inversores', '0002_inversor_temperatura_limite_c'),
    ]

    operations = [
        migrations.AddField(
            model_name='inversor',
            name='tipo_ligacao',
            field=models.CharField(blank=True, choices=[('monofasico', 'Monofásica'), ('bifasico', 'Bifásica'), ('trifasico', 'Trifásica')], help_text='Última classificação não-null vinda do adapter. Atualizado pela ingestão de coleta — preserva a classificação mesmo quando a leitura mais recente vem com tipo null (inversor offline / fim de tarde sem fases energizadas).', max_length=20, null=True),
        ),
    ]
