# Generated by Django 5.1.15 on 2026-04-24 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
        ('provedores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_externo', models.CharField(blank=True, default='', max_length=128)),
                ('nome', models.CharField(max_length=200)),
                ('endereco', models.CharField(blank=True, default='', max_length=500)),
                ('cidade', models.CharField(blank=True, default='', max_length=120)),
                ('estado', models.CharField(blank=True, default='', max_length=2)),
                ('cep', models.CharField(blank=True, default='', max_length=10)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='Preenchido manualmente ou via geocoding (fora do MVP).', max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('fuso_horario', models.CharField(blank=True, default='America/Sao_Paulo', max_length=50)),
                ('capacidade_kwp', models.DecimalField(blank=True, decimal_places=3, help_text='Valor do provedor. Validar > 0; FusionSolar às vezes devolve 0.008 (bug).', max_digits=10, null=True)),
                ('comissionada_em', models.DateField(blank=True, null=True)),
                ('tipo_equipamento', models.CharField(choices=[('inversor', 'Inversor'), ('microinversor', 'Microinversor'), ('indefinido', 'Indefinido')], default='indefinido', help_text='Preenchido pelo adapter ou pelo usuário.', max_length=20)),
                ('expoe_dados_inversor', models.BooleanField(default=False, help_text='Se True, o worker coleta também dados por inversor (tabelas `Inversor` e `LeituraInversor`). Valor derivado de `CapacidadesProvedor` no adapter na primeira coleta.')),
                ('tensao_ac_limite_v', models.DecimalField(decimal_places=1, default=240, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('ultima_leitura_em', models.DateTimeField(blank=True, help_text='Cache denormalizado de `LeituraUsina.medido_em` mais recente.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conta_provedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usinas', to='provedores.contaprovedor')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Usina',
                'verbose_name_plural': 'Usinas',
                'indexes': [models.Index(fields=['empresa', 'is_active'], name='usinas_usin_empresa_4a19bb_idx'), models.Index(fields=['conta_provedor', 'id_externo'], name='usinas_usin_conta_p_a36422_idx'), models.Index(fields=['empresa', 'ultima_leitura_em'], name='usinas_usin_empresa_2d126c_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('id_externo', ''), _negated=True), fields=('conta_provedor', 'id_externo'), name='usina_unique_id_externo_por_conta')],
            },
        ),
    ]
