# Generated by Django 5.1.15 on 2026-04-24 22:32

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usinas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usina',
            name='frequencia_maximo_hz',
            field=models.DecimalField(decimal_places=2, default=Decimal('60.5'), help_text='Limite superior de frequência AC (regra frequencia_anomala).', max_digits=4),
        ),
        migrations.AddField(
            model_name='usina',
            name='frequencia_minimo_hz',
            field=models.DecimalField(decimal_places=2, default=Decimal('59.5'), help_text='Limite inferior de frequência AC (regra frequencia_anomala).', max_digits=4),
        ),
        migrations.AddField(
            model_name='usina',
            name='tensao_ac_limite_minimo_v',
            field=models.DecimalField(decimal_places=1, default=200, help_text='Limite inferior de tensão AC (regra subtensao_ac).', max_digits=5),
        ),
        migrations.AlterField(
            model_name='usina',
            name='tensao_ac_limite_v',
            field=models.DecimalField(decimal_places=1, default=240, help_text='Limite superior de tensão AC (regra sobretensao_ac).', max_digits=5),
        ),
    ]
