# Generated by Django 5.1.15 on 2026-04-24 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usinas', '0002_usina_frequencia_maximo_hz_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usina',
            name='estado',
            field=models.CharField(blank=True, default='', help_text="UF (ex. 'SC') ou nome completo — adapters variam.", max_length=50),
        ),
    ]
