# Generated by Django 5.1.15 on 2026-04-26 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usinas', '0003_alter_usina_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usina',
            name='tensao_ac_limite_minimo_v',
            field=models.DecimalField(decimal_places=1, default=190, help_text='Limite inferior de tensão AC (regra subtensao_ac).', max_digits=5),
        ),
    ]
