# Generated by Django 5.1.15 on 2026-04-27 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usinas', '0005_aplicar_calibracao_subtensao'),
    ]

    operations = [
        migrations.AddField(
            model_name='usina',
            name='tensao_nominal_v',
            field=models.IntegerField(choices=[(110, '110 V (Bifásica/Monofásica 127V)'), (220, '220 V (Bifásica/Trifásica 220V)')], default=220, help_text="Tensão nominal da rede onde a usina está conectada. Define o threshold de subtensão (85% do nominal) e sobretensão (110%). Para a opção '110 V' adota-se 127 V como nominal efetivo (NBR 5410 / ABNT) — faixa típica 108–140 V. Pode ser sobrescrita pelos campos `tensao_ac_limite_minimo_v` e `tensao_ac_limite_v` se preenchidos manualmente."),
        ),
        migrations.AlterField(
            model_name='usina',
            name='tensao_ac_limite_minimo_v',
            field=models.DecimalField(decimal_places=1, default=190, help_text='Limite inferior de tensão AC (regra subtensao_ac). Quando diferente do default (190) sobrescreve o cálculo automático derivado de `tensao_nominal_v` (85% do nominal).', max_digits=5),
        ),
        migrations.AlterField(
            model_name='usina',
            name='tensao_ac_limite_v',
            field=models.DecimalField(decimal_places=1, default=240, help_text='Limite superior de tensão AC (regra sobretensao_ac). Quando diferente do default (240) sobrescreve o cálculo automático derivado de `tensao_nominal_v` (110% do nominal).', max_digits=5),
        ),
    ]
