# Generated by Django 5.1.15 on 2026-05-06 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usinas', '0007_usina_bairro_alter_usina_latitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usina',
            name='tensao_ac_limite_minimo_v',
            field=models.DecimalField(decimal_places=1, default=190, help_text='Limite inferior de tensão AC (regra subtensao_ac). Quando diferente do default (190) sobrescreve o cálculo automático derivado de `tensao_nominal_v` (91% do nominal — 220V → 200V).', max_digits=5),
        ),
        migrations.AlterField(
            model_name='usina',
            name='tensao_nominal_v',
            field=models.IntegerField(choices=[(110, '127V (Monofásica/Bifásica)'), (220, '220V (Monofásica/Bifásica/Trifásica)')], default=220, help_text="Tensão nominal da rede onde a usina está conectada. Define o threshold de subtensão (91% do nominal — 220V → 200V) e sobretensão (110% do nominal — 220V → 242V). Para a opção '110 V' adota-se 127 V como nominal efetivo (NBR 5410 / ABNT) — faixa típica 108–140 V. Pode ser sobrescrita pelos campos `tensao_ac_limite_minimo_v` e `tensao_ac_limite_v` se preenchidos manualmente."),
        ),
    ]
