# Generated by Django 5.1.15 on 2026-04-24 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
        ('inversores', '0001_initial'),
        ('usinas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regra', models.CharField(help_text='Identificador da regra. Ex.: `sem_comunicacao`, `sobretensao_ac`, `sem_geracao_horario_solar`. Casa com o módulo em `alertas/regras/`.', max_length=60)),
                ('severidade', models.CharField(choices=[('info', 'Informativo'), ('aviso', 'Aviso'), ('critico', 'Crítico')], max_length=20)),
                ('estado', models.CharField(choices=[('aberto', 'Aberto'), ('reconhecido', 'Reconhecido'), ('resolvido', 'Resolvido')], default='aberto', max_length=20)),
                ('mensagem', models.TextField(help_text="Texto legível. Ex.: 'Tensão AC 251.3 V acima do limite (240 V).'")),
                ('contexto', models.JSONField(blank=True, default=dict, help_text='Snapshot dos valores que dispararam/atualizaram o alerta. Ex.: {"tensao_ac_v": 251.3, "limite": 240, "leitura_id": "..."}.')),
                ('aberto_em', models.DateTimeField(auto_now_add=True)),
                ('resolvido_em', models.DateTimeField(blank=True, null=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='empresas.empresa')),
                ('inversor', models.ForeignKey(blank=True, help_text='Preenchido quando a regra é por equipamento (ex.: inversor_offline, sobretensao_ac). Null para regras de usina (ex.: sem_geracao_horario_solar, sem_comunicacao).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='inversores.inversor')),
                ('usina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='usinas.usina')),
            ],
            options={
                'verbose_name': 'Alerta',
                'verbose_name_plural': 'Alertas',
                'ordering': ('-aberto_em',),
                'indexes': [models.Index(fields=['empresa', 'estado', '-aberto_em'], name='alertas_ale_empresa_e99bd2_idx'), models.Index(fields=['usina', 'estado'], name='alertas_ale_usina_i_0402c4_idx'), models.Index(fields=['regra', 'estado'], name='alertas_ale_regra_a55a71_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('estado', 'aberto')), fields=('usina', 'inversor', 'regra'), name='alerta_unico_aberto_por_regra')],
            },
        ),
    ]
