# Generated by Django 5.1.15 on 2026-05-06 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alertas', '0001_initial'),
        ('empresas', '0002_cidade_uf'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoRegra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regra_nome', models.CharField(db_index=True, help_text='Identificador da regra. Casa com `cls.nome` em `apps/alertas/regras/<nome>.py`.', max_length=64)),
                ('ativa', models.BooleanField(default=True, help_text='Quando False, o motor pula essa regra para a empresa.')),
                ('severidade', models.CharField(choices=[('info', 'Informativo'), ('aviso', 'Aviso'), ('critico', 'Crítico')], help_text='Sobrescreve `severidade_padrao` da regra. Ignorado para regras com severidade dinâmica (ex.: `sem_comunicacao`, `garantia_vencendo`).', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configuracoes_regra', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Configuração de regra',
                'verbose_name_plural': 'Configurações de regras',
                'indexes': [models.Index(fields=['empresa', 'regra_nome'], name='alertas_con_empresa_4d10e5_idx')],
                'constraints': [models.UniqueConstraint(fields=('empresa', 'regra_nome'), name='configuracaoregra_unica_por_empresa_regra')],
            },
        ),
    ]
